# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            export SLUGIFY_USES_TEXT_UNIDECODE=yes
            pip install -e .
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      # Run (pytest) tests.
      # https://pytest.org
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest
      - store_artifacts:
          path: test-reports
          destination: test-reports

  lint:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-lint-dependencies-{{ checksum ".circleci/lint-requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-lint-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r .circleci/lint-requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: lint
          command: |
            . venv/bin/activate
            black --check --exclude venv .
  
workflows:
  process_pr:
    jobs:
      - build
      - lint